<?php ! defined( 'ABSPATH' ) AND exit( 'Forbidden!' );

/*! ===================================
 *  Author: Roman Nazarkin, Egor Dankov
 *  -----------------------------------
 *  PuzzleThemes
 *  =================================== */


if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_59bcc010a8503',
		'title' => 'Custom sidebar options',
		'fields' => array (
			array (
				'key' => 'field_59bcc7914efd1',
				'label' => esc_html__('Hide sidebar', 'soprano-ecommerce'),
				'name' => 'hide_sidebar',
				'type' => 'true_false',
				'instructions' => esc_html__('This option allows you to hide sidebar on that particular page.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Yes',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_59bcc73b4efce',
				'label' => esc_html__('Sidebar position', 'soprano-ecommerce'),
				'name' => 'sidebar_position',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59bcc7914efd1',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'inherit' => esc_html__('Inherit from theme options', 'soprano-ecommerce'),
					'Left' => esc_html__('Left', 'soprano-ecommerce'),
					'Right' => esc_html__('Right', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_59bcc7d54efd2',
				'label' => esc_html__('Make sidebar sticky', 'soprano-ecommerce'),
				'name' => 'make_sidebar_sticky',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59bcc7914efd1',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'inherit' => esc_html__('Inherit from theme options', 'soprano-ecommerce'),
					'Yes' => esc_html__('Yes', 'soprano-ecommerce'),
					'No' => esc_html__('No', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b3771991aec',
		'title' => esc_html__('Audio/Video post options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b3776a51455',
				'label' => esc_html__('oEmbed URL', 'soprano-ecommerce'),
				'name' => 'oembed',
				'type' => 'oembed',
				'instructions' => esc_html__('Paste oEmbed URL of audio/video fragment.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'width' => '',
				'height' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
				),
			),
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b829cc5fb95',
		'title' => esc_html__('Blogroll page options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b82b4fc0ceb',
				'label' => esc_html__('Listing layout', 'soprano-ecommerce'),
				'name' => 'listing_layout',
				'type' => 'radio',
				'instructions' => esc_html__('Select layout to use on this particular page.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Inherit' => esc_html__('Inherit from global theme options', 'soprano-ecommerce'),
					'Chess' => esc_html__('Chess', 'soprano-ecommerce'),
					'Medium' => esc_html__('Medium', 'soprano-ecommerce'),
					'Classic' => esc_html__('Classic', 'soprano-ecommerce'),
					'Masonry' => esc_html__('Masonry', 'soprano-ecommerce')
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_59bf70e482ee9',
				'label' => esc_html__('Posts per page', 'soprano-ecommerce'),
				'name' => 'posts_per_page',
				'type' => 'number',
				'instructions' => esc_html__('Leave empty to use global value from WordPress options.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'blogroll-template.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b2767148976',
		'title' => esc_html__('Gallery post options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b27688e5d5e',
				'label' => esc_html__('Images', 'soprano-ecommerce'),
				'name' => 'images',
				'type' => 'repeater',
				'instructions' => esc_html__('Attach images to this blog post.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_59b276d7e5d60',
				'min' => 2,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add image',
				'sub_fields' => array (
					array (
						'key' => 'field_59b276c5e5d5f',
						'label' => esc_html__('Image', 'soprano-ecommerce'),
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array (
						'key' => 'field_59b276d7e5d60',
						'label' => esc_html__('Caption', 'soprano-ecommerce'),
						'name' => 'caption',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_599c5835c9603',
		'title' => esc_html__('General', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_599c6077e5208',
				'label' => esc_html__('Fonts', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c583f5b4ec',
				'label' => esc_html__('Primary font', 'soprano-ecommerce'),
				'name' => 'primary_font',
				'type' => 'google_font_selector',
				'instructions' => esc_html__('The most frequently used font family in the theme. Used in text paragraphs, menus, widgets and more.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'include_web_safe_fonts' => 0,
				'enqueue_font' => 0,
				'default_font' => 'Source Sans Pro',
			),
			array (
				'key' => 'field_599c59625b4ed',
				'label' => esc_html__('Headings font', 'soprano-ecommerce'),
				'name' => 'headings_font',
				'type' => 'google_font_selector',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'include_web_safe_fonts' => 0,
				'enqueue_font' => 0,
				'default_font' => 'Montserrat',
			),
			array (
				'key' => 'field_599c59ac5b4ee',
				'label' => esc_html__('Accent font', 'soprano-ecommerce'),
				'name' => 'accent_font',
				'type' => 'google_font_selector',
				'instructions' => esc_html__('Used in quotes and hero blocks.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'include_web_safe_fonts' => 0,
				'enqueue_font' => 0,
				'default_font' => 'Shadows Into Light',
			),
			array (
				'key' => 'field_599c607fe5209',
				'label' => esc_html__('Colors', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c59f85b4f1',
				'label' => esc_html__('Primary color', 'soprano-ecommerce'),
				'name' => 'primary_color',
				'type' => 'color_picker',
				'instructions' => esc_html__('The main branding color of your site. Used in buttons, headings, backgrounds and etc.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#C3AC6D',
			),
			array (
				'key' => 'field_59bad552b1efb',
				'label' => esc_html__('Body background color', 'soprano-ecommerce'),
				'name' => 'body_bg_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_599c5a0d5b4f2',
				'label' => esc_html__('Body text color', 'soprano-ecommerce'),
				'name' => 'body_text_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#333',
			),
			array (
				'key' => 'field_59bcbc8db7c76',
				'label' => esc_html__('Sidebars', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_59bcbcb3b7c77',
				'label' => esc_html__('Sidebar position', 'soprano-ecommerce'),
				'name' => 'sidebar_position_global',
				'type' => 'radio',
				'instructions' => esc_html__('Select page side for sidebar.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Left' => esc_html__('Left', 'soprano-ecommerce'),
					'Right' => esc_html__('Right', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_59bcbce8b7c78',
				'label' => esc_html__('Make sidebar sticky', 'soprano-ecommerce'),
				'name' => 'make_sidebar_sticky_global',
				'type' => 'radio',
				'instructions' => esc_html__('If this option in turned on - sidebar will stick on user\'s screen when scrolling.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Yes' => esc_html__('Yes', 'soprano-ecommerce'),
					'No' => esc_html__('No', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c608be520a',
				'label' => esc_html__('Other', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c6097e520b',
				'label' => esc_html__('Google Maps API key', 'soprano-ecommerce'),
				'name' => 'google_maps_api_key',
				'type' => 'text',
				'instructions' => wp_kses_post(__('Enter your own key in order to enable Google services in a theme. <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">Create new key.</a>', 'soprano-ecommerce')),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_599c5ae9a0b90',
				'label' => esc_html__('Site socials', 'soprano-ecommerce'),
				'name' => 'social_networks',
				'type' => 'repeater',
				'instructions' => esc_html__('Leave empty to hide social links from the website.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_599c5b33a0b92',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add new button',
				'sub_fields' => array (
					array (
						'key' => 'field_599c5b0aa0b91',
						'label' => esc_html__('Icon', 'soprano-ecommerce'),
						'name' => 'profile_icon',
						'type' => 'fonticonpicker',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'key' => 'field_599c5b33a0b92',
						'label' => esc_html__('URL', 'soprano-ecommerce'),
						'name' => 'profile_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array (
				'key' => 'field_599c6241e520c',
				'label' => esc_html__('Default intro background', 'soprano-ecommerce'),
				'name' => 'default_intro_background',
				'type' => 'image',
				'instructions' => esc_html__('Upload default intro block background for search results pages and simple static pages.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium_large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_599c736bcc7a6',
				'label' => esc_html__('"Go to top" button', 'soprano-ecommerce'),
				'name' => 'go_to_top_button',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Enabled' => esc_html__('Enabled', 'soprano-ecommerce'),
					'Disabled' => esc_html__('Disabled', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'sp-theme-general-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b2727ceca7e',
		'title' => esc_html__('Image post options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b272945e2f7',
				'label' => esc_html__('Image', 'soprano-ecommerce'),
				'name' => 'image',
				'type' => 'image',
				'instructions' => esc_html__('Uploaded image will be shown on single page of that blog post.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium_large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_59b272c15e2f8',
				'label' => esc_html__('Caption', 'soprano-ecommerce'),
				'name' => 'caption',
				'type' => 'textarea',
				'instructions' => esc_html__('Basic HTML is allowed. Can be empty.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'image',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b274efe3f60',
		'title' => esc_html__('Link post options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b274feb7b81',
				'label' => esc_html__('Link', 'soprano-ecommerce'),
				'name' => 'link',
				'type' => 'url',
				'instructions' => esc_html__('Attach here a link that will be featured in this post.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'link',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59b27563811a9',
		'title' => esc_html__('Quote post options', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_59b27585f7e3a',
				'label' => esc_html__('Quote text', 'soprano-ecommerce'),
				'name' => 'quote_text',
				'type' => 'textarea',
				'instructions' => esc_html__('Type featured quote of this post. Basic HTML is allowed.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'wpautop',
			),
			array (
				'key' => 'field_59b275aaf7e3b',
				'label' => esc_html__('Quote author', 'soprano-ecommerce'),
				'name' => 'quote_author',
				'type' => 'text',
				'instructions' => esc_html__('Will be shown under quote text.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'quote',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_599c635466aee',
		'title' => esc_html__('Header', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_599c636842de2',
				'label' => esc_html__('Logo type', 'soprano-ecommerce'),
				'name' => 'logo_type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'image' => esc_html__('Image', 'soprano-ecommerce'),
					'text' => esc_html__('Text', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'text',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c63c642de3',
				'label' => esc_html__('Light logo image', 'soprano-ecommerce'),
				'name' => 'logo_image_light',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_599c636842de2',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium_large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_599c65ee42de5',
				'label' => esc_html__('Dark logo image', 'soprano-ecommerce'),
				'name' => 'logo_image_dark',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_599c636842de2',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium_large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_59f5ab806b511',
				'label' => esc_html__('Logo height', 'soprano-ecommerce'),
				'name' => 'logo_height',
				'type' => 'number',
				'instructions' => esc_html__('Logo image will be resized automatically to this height.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_599c636842de2',
							'operator' => '==',
							'value' => 'image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 50,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 50,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_599c682d42de6',
				'label' => esc_html__('Logo text', 'soprano-ecommerce'),
				'name' => 'logo_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_599c636842de2',
							'operator' => '==',
							'value' => 'text',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Soprano',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_599c683e42de7',
				'label' => esc_html__('Highlight first letter', 'soprano-ecommerce'),
				'name' => 'highlight_first_letter',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_599c636842de2',
							'operator' => '==',
							'value' => 'text',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Yes' => esc_html__('Yes', 'soprano-ecommerce'),
					'No' => esc_html__('No', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Yes',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c8c6656deb',
				'label' => esc_html__('Header stuck effect', 'soprano-ecommerce'),
				'name' => 'header_stuck_effect',
				'type' => 'radio',
				'instructions' => esc_html__('How effect should be applied to the header when a page gets scrolled down.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'stuck-transform' => esc_html__('Transform', 'soprano-ecommerce'),
					'stuck-slidein' => esc_html__('Slide-in from top', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'stuck-slidein',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c6962247bf',
				'label' => esc_html__('Hide search from header', 'soprano-ecommerce'),
				'name' => 'hide_search_from_header',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Yes' => esc_html__('Yes', 'soprano-ecommerce'),
					'No' => esc_html__('No', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'No',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'sp-theme-header-options',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_599c69c14a5ee',
		'title' => esc_html__('Footer', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_599c69cc0a138',
				'label' => esc_html__('Widget columns', 'soprano-ecommerce'),
				'name' => 'footer_widget_columns',
				'type' => 'number',
				'instructions' => esc_html__('Select how much columns should be present in the footer widgets area.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 4,
				'step' => 1,
			),
			array (
				'key' => 'field_599c6abd0a139',
				'label' => esc_html__('Background color', 'soprano-ecommerce'),
				'name' => 'footer_background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#222',
			),
			array (
				'key' => 'field_599c6b490a13a',
				'label' => esc_html__('Text color', 'soprano-ecommerce'),
				'name' => 'footer_text_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#fff',
			),
			array (
				'key' => 'field_599c6b6b0a13b',
				'label' => esc_html__('Links color', 'soprano-ecommerce'),
				'name' => 'footer_links_color',
				'type' => 'color_picker',
				'instructions' => esc_html__('By default equals to a primary color.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_599c6b920a13c',
				'label' => esc_html__('Copyright text', 'soprano-ecommerce'),
				'name' => 'footer_copyright_text',
				'type' => 'textarea',
				'instructions' => wp_kses_post(__('<code>@YEAR</code> is equals to current year.', 'soprano-ecommerce')),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '&copy; 2018 Soprano by <a href="https://themeforest.net/user/puzzlethemes?ref=PuzzleThemes">PuzzleThemes</a>. All right reserved.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'new_lines' => 'br',
			),
			array (
				'key' => 'field_599c6c0f0a13d',
				'label' => esc_html__('Footer mode', 'soprano-ecommerce'),
				'name' => 'footer_mode',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'sp-footer-regular' => esc_html__('Regular', 'soprano-ecommerce'),
					'sp-footer-fixed' => esc_html__('Fixed with fade', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'sp-footer-regular',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'sp-theme-footer-options',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_599c6c5424c88',
		'title' => esc_html__('Theme extras', 'soprano-ecommerce'),
		'fields' => array (
			array (
				'key' => 'field_599c6ce49395a',
				'label' => esc_html__('Blog', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c6cf59395b',
				'label' => esc_html__('Listing layout', 'soprano-ecommerce'),
				'name' => 'blog_listing_layout',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Chess' => esc_html__('Chess', 'soprano-ecommerce'),
					'Medium' => esc_html__('Medium', 'soprano-ecommerce'),
					'Classic' => esc_html__('Classic', 'soprano-ecommerce'),
					'Masonry' => esc_html__('Masonry', 'soprano-ecommerce')
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Classic',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c6dd19395e',
				'label' => esc_html__('Related posts mechanism', 'soprano-ecommerce'),
				'name' => 'related_posts_mechanism',
				'type' => 'radio',
				'instructions' => esc_html__('Select none to disable "related posts" feature.', 'soprano-ecommerce'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Tags' => esc_html__('Tags', 'soprano-ecommerce'),
					'Categories' => esc_html__('Categories', 'soprano-ecommerce'),
					'None' => esc_html__('None', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_599c6f745e9af',
				'label' => esc_html__('Mailchimp subscription form', 'soprano-ecommerce'),
				'name' => 'mailchimp_subscription_form',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array (
					array (
						'key' => 'field_599c6f8b5e9b0',
						'label' => esc_html__('Enabled', 'soprano-ecommerce'),
						'name' => 'enabled',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Yes',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array (
						'key' => 'field_599c6fc65e9b1',
						'label' => esc_html__('Form URL', 'soprano-ecommerce'),
						'name' => 'form_url',
						'type' => 'text',
						'instructions' => esc_html__('This should be something like http://xxxx.us9.list-manage.com/subscribe/post?u=1368c473b42d831e481262a9c&id=63bbf421ee', 'soprano-ecommerce'),
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_599c6f8b5e9b0',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_599c701e5e9b2',
						'label' => esc_html__('Form heading', 'soprano-ecommerce'),
						'name' => 'heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_599c6f8b5e9b0',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Subscribe To Our Newsletter',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array (
						'key' => 'field_599c702f5e9b3',
						'label' => esc_html__('Form opening text', 'soprano-ecommerce'),
						'name' => 'opening_text',
						'type' => 'textarea',
						'instructions' => esc_html__('Basic HTML is allowed.', 'soprano-ecommerce'),
						'required' => 0,
						'conditional_logic' => array (
							array (
								array (
									'field' => 'field_599c6f8b5e9b0',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 4,
						'new_lines' => 'wpautop',
					),
				),
			),
			array (
				'key' => 'field_599c6c6193958',
				'label' => esc_html__('Portfolio', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c6c6c93959',
				'label' => esc_html__('Slug base', 'soprano-ecommerce'),
				'name' => 'portfolio_slug_base',
				'type' => 'text',
				'instructions' => esc_html__('Used in permalinks for portfolio single item pages. Leave empty to use theme-default.', 'soprano-ecommerce'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'portfolio',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_599c71e2140c0',
				'label' => esc_html__('404 Page', 'soprano-ecommerce'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_599c71e8140c1',
				'label' => esc_html__('Main headline', 'soprano-ecommerce'),
				'name' => '404_main_headline',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '404 Error',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_599c71ff140c2',
				'label' => esc_html__('Headline subscript', 'soprano-ecommerce'),
				'name' => '404_headline_subscript',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Houston, We Have A Problem',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_599c7212140c3',
				'label' => esc_html__('Background image', 'soprano-ecommerce'),
				'name' => '404_background_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'medium_large',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_599c7223140c4',
				'label' => esc_html__('Enable Ken Burns effect', 'soprano-ecommerce'),
				'name' => '404_ken_burns_effect',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Yes' => esc_html__('Yes', 'soprano-ecommerce'),
					'No' => esc_html__('No', 'soprano-ecommerce'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'sp-theme-extras-options',
				),
			),
		),
		'menu_order' => 15,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;